### ISSUE TITLE
Request body should be made generic

### ISSUE THREAD

**Issue by nicholas-eden** [gomodule/oauth1#43]
It is impossible to make json requests because the methods require `url.Values`.   You could leave those in for backwards compatibility and make the `do` function public and accept `http.Request` so the library would handle the authentication and the client code can build the request data in whatever format they need.

**Comment by MindyJackson** [comment]
How is the signature computed for a JSON body?  The specification only mentions how to compute the signature for a form.

**Comment by garyburd** [comment]
Use the lower-level [SetAuthorizationHeader](https://godoc.org/github.com/gomodule/oauth1/oauth#Client.SetAuthorizationHeader) method to add an authorization header to a [request header](https://godoc.org/net/http#Request.Header).  Here's a sketch of the code:

	req, err := http.NewRequest(method, urlStr, body)
	if err != nil {
		return nil, err
	}
         client.setAuthorizationHeader(req.Header, credentials, req.Method, req.URL, form)
         resp, err := client.Do(req)

The package does not have a higher-level helper function for your scenario because the Oauth specs do not cover scenario where the request body is not a form.
